name: CI

on:
  - push

jobs:

  build-on-linux:
    runs-on: ubuntu-latest

    steps:
      - uses: szenius/set-timezone@v1.2
        with:
          timezoneLinux: "Asia/Singapore"
          timezoneMacos: "Asia/Singapore"
          timezoneWindows: "Singapore Standard Time"
      - uses: actions/checkout@v3
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.20"
      - name: Install dependencies
        run: go mod tidy
      - name: build all versions
        run: make build
      - name: Upload linux binaries
        uses: actions/upload-artifact@v3
        with:
          name: linux-binaries
          path: ./dist/
      - name: Run the code directly
        run: go run main.go
      - name: Run built code
        run: ./dist/main_local


  build-on-macos:
    runs-on: macos-latest

    steps:
      - uses: szenius/set-timezone@v1.2
        with:
          timezoneLinux: "Asia/Singapore"
          timezoneMacos: "Asia/Singapore"
          timezoneWindows: "Singapore Standard Time"
      - uses: actions/checkout@v3
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.20"
      - name: Install dependencies
        run: go mod tidy
      - name: build all versions
        run: make build
      - name: Upload macos binaries
        uses: actions/upload-artifact@v3
        with:
          name: macos-binaries
          path: ./dist/
      - name: Run the code directly
        run: go run main.go
      - name: Run built code
        run: ./dist/main_local

  docker-on-linux:
    runs-on: ubuntu-latest
    container:
      image: golang:1.20.3-bullseye
      env:
        TZ: "America/New_York"
    needs:
      - build-on-linux
      - build-on-macos

    steps:
      - name: set timezone
        run: apt update && apt install tzdata -y
      - name: check timezone
        run: date && date -u
      - uses: actions/checkout@v3
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.20"
      - name: Run the code directly
        run: go run main.go
      - name: Download the linux binaries
        uses: actions/download-artifact@v3
        with:
          name: linux-binaries
          path: ./dist_linux/
      - name: fix file permissions
        run: chmod +x ./dist_linux/*
      - name: Run the pre built code from linux
        run: ./dist_linux/main_linux_amd64
      - name: Download the macos binaries
        uses: actions/download-artifact@v3
        with:
          name: macos-binaries
          path: ./dist_macos/
      - name: fix file permissions
        run: chmod +x ./dist_macos/*
      - name: Run the pre built code from macos
        run: ./dist_macos/main_darwin_amd64
